updated form-fields styling when autofilled
plone/pastanaga-angular pull request #285
Opened 2020-09-09 13:32 UTC by julienCarret

I also added an enum that can help choose proper input name 
or let's us find out if "name" attribute is going to be autofilled properly or not by browsers.

2020-09-09 15:13 UTC, mpellerin42 requested changes

2020-09-09 15:13 UTC, mpellerin42 commented on projects/pastanaga-angular/src/lib/styles/_textfields.scss
> +                background: linear-gradient(180deg, #FFFFFF 62.42%, rgba(229, 243, 255, 0) 63.83%, $color-background-field-autofilled 100%);
no `#FFFFFF` nor `rgba(229, 243, 255, 0)`, use tokens instead

2020-09-09 15:49 UTC, julienCarret commented on projects/pastanaga-angular/src/lib/styles/_textfields.scss
> +                background: linear-gradient(180deg, #FFFFFF 62.42%, rgba(229, 243, 255, 0) 63.83%, $color-background-field-autofilled 100%);
sure

2020-09-10 06:59 UTC, mpellerin42 approved these changes

2020-09-10 07:05 UTC, merged