Focusable and tabs
plone/pastanaga-angular pull request #314
Opened 2020-10-29 17:03 UTC by julienCarret

2020-10-29 17:25 UTC, jlp0328 approved these changes

2020-10-30 08:21 UTC, mpellerin42 requested changes

2020-10-30 08:21 UTC, mpellerin42 commented on projects/demo/src/app/demo/pages/focusable-page/focusable-page.component.html
> +    </p>
indentation

2020-10-30 08:21 UTC, mpellerin42 commented on projects/pastanaga-angular/src/lib/tabs/tabs-list.component.ts
> +    }
the default is true: full width by default. so the Input should be something allowing to not have full width, so `noFullWidth` for example. I guess in most cases this won't be set dynamically: we want either full width or no full width on an element. Doing it this way will allow us to have code like
```html
<pa-tabs noFullWidth>…
```

2020-10-30 08:21 UTC, mpellerin42 commented on projects/pastanaga-angular/src/lib/table/table-cell-menu/table-cell-menu.component.spec.ts
> +import { PaFocusableModule } from '../../..';
wrong import

2020-10-30 08:21 UTC, mpellerin42 commented on projects/pastanaga-angular/src/lib/table/table.spec.ts
> +import { PaFocusableModule } from '../..';
wrong import

2020-10-30 09:08 UTC, mpellerin42 approved these changes

2020-10-30 09:14 UTC, merged