date-picker
plone/pastanaga-angular pull request #568
Opened 2022-04-25 03:11 UTC by dgsmith2

2022-04-25 03:11 UTC, mister-roboto commented
Daniel Smith your emails are not known to GitHub and thus it is impossible to know if you have signed the Plone Contributor Agreement, which is required to merge this pull request.

Learn about the Plone Contributor Agreement: http://docs.plone.org/develop/coredev/docs/contributors_agreement_explained.html How to add more emails to your GitHub account: https://help.github.com/articles/adding-an-email-address-to-your-github-account/

2022-04-25 06:42 UTC, ebrehault commented
Hi @dgsmith2 ! Glad to see you're preparing a PR on Pastanaga :)

Apparently you've removed your email address from your GitHub profile so it is not associated anymore to your Contributor Agreement, and it will prevent the PR to be merged.
If that was a professional email you don't have anymore, I guess you can contact @ableeb, he should be able to reference a different email.

2022-04-25 16:17 UTC, barcafa commented on projects/pastanaga-angular/src/lib/date-picker/date-picker.component.scss
> +        color: #001530;
`$color-dark-stronger`?

2022-04-25 16:19 UTC, barcafa commented on projects/pastanaga-angular/src/lib/date-picker/date-picker.component.scss
> +            color: #e3e7eb;
`$color-neutral-light`?

2022-04-25 16:20 UTC, barcafa commented on projects/pastanaga-angular/src/lib/date-picker/date-picker.component.scss
> +            background-color: #e5f3ff;
`$color-primary-lightest`

2022-04-25 16:20 UTC, barcafa commented on projects/pastanaga-angular/src/lib/date-picker/date-picker.component.scss
> +        background-color: #e5f3ff;
`$color-primary-lightest`

2022-04-25 16:21 UTC, barcafa commented on projects/pastanaga-angular/src/lib/date-picker/date-picker.component.scss
> +            background-color: #f2f5f7;
`$color-neutral-lighter`

2022-05-03 02:21 UTC, mister-roboto commented
Daniel Smith your emails are not known to GitHub and thus it is impossible to know if you have signed the Plone Contributor Agreement, which is required to merge this pull request.

Learn about the Plone Contributor Agreement: http://docs.plone.org/develop/coredev/docs/contributors_agreement_explained.html How to add more emails to your GitHub account: https://help.github.com/articles/adding-an-email-address-to-your-github-account/

2022-05-06 09:27 UTC, mpellerin42 requested changes

2022-05-06 09:27 UTC, mpellerin42 commented on projects/pastanaga-angular/src/lib/date-picker/date-picker.component.scss
> +    --day-width: 32px;
replace all pixel values by rhythm.

2022-05-06 09:27 UTC, mpellerin42 commented on projects/pastanaga-angular/src/lib/date-picker/date-picker.component.scss
> +        padding: 6px 0;
6px is not part of our rhythm map, so there is a big chance that this value is wrong, or meant to be coming from some alignment flex rule more than a static padding.

2022-05-08 00:18 UTC, dgsmith2 commented on projects/pastanaga-angular/src/lib/date-picker/date-picker.component.ts
> +                debounceTime(500),
I'll make this change but not 100% on board.  A constant (named) for css/animation is being used in a context that has nothing to do with it.

2022-05-09 11:17 UTC, julienCarret commented on projects/pastanaga-angular/src/lib/date-picker/date-picker.component.ts
> +        this.disabled = disabled;
should we add this.formControl.disable() ?

2022-05-09 11:19 UTC, julienCarret commented on projects/pastanaga-angular/src/lib/translate/i18n/en.ts
> +    },
We could have the months here to...

2022-05-09 11:21 UTC, julienCarret approved these changes

2022-05-09 12:13 UTC, mpellerin42 commented on projects/pastanaga-angular/src/lib/date-picker/date-picker.component.scss
>          text-transform: uppercase;
seems like you could have used pastanaga typography class `.overline` here.
You can see all the typography classes in https://github.com/plone/pastanaga-angular/blob/a09a31d30635fc381ae7aeb0537052fef7aa92e6/projects/pastanaga-angular/src/styles/_typography.scss

2022-05-11 12:18 UTC, mpellerin42 approved these changes

2022-05-12 11:29 UTC, merged